/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as GuestIndexRouteImport } from './routes/_guest/index'
import { Route as AuthedARouteRouteImport } from './routes/_authed/a/route'
import { Route as AuthedAIndexRouteImport } from './routes/_authed/a/index'
import { Route as AuthedAUsersRouteImport } from './routes/_authed/a/users'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthedARouteRoute = AuthedARouteRouteImport.update({
  id: '/a',
  path: '/a',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAIndexRoute = AuthedAIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedARouteRoute,
} as any)
const AuthedAUsersRoute = AuthedAUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedARouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/a': typeof AuthedARouteRouteWithChildren
  '/': typeof GuestIndexRoute
  '/a/users': typeof AuthedAUsersRoute
  '/a/': typeof AuthedAIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof GuestIndexRoute
  '/a/users': typeof AuthedAUsersRoute
  '/a': typeof AuthedAIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_authed/a': typeof AuthedARouteRouteWithChildren
  '/_guest/': typeof GuestIndexRoute
  '/_authed/a/users': typeof AuthedAUsersRoute
  '/_authed/a/': typeof AuthedAIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/a' | '/' | '/a/users' | '/a/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/a/users' | '/a'
  id:
    | '__root__'
    | '/_authed'
    | '/_guest'
    | '/_authed/a'
    | '/_guest/'
    | '/_authed/a/users'
    | '/_authed/a/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/': {
      id: '/_guest/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_authed/a': {
      id: '/_authed/a'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof AuthedARouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/a/': {
      id: '/_authed/a/'
      path: '/'
      fullPath: '/a/'
      preLoaderRoute: typeof AuthedAIndexRouteImport
      parentRoute: typeof AuthedARouteRoute
    }
    '/_authed/a/users': {
      id: '/_authed/a/users'
      path: '/users'
      fullPath: '/a/users'
      preLoaderRoute: typeof AuthedAUsersRouteImport
      parentRoute: typeof AuthedARouteRoute
    }
  }
}

interface AuthedARouteRouteChildren {
  AuthedAUsersRoute: typeof AuthedAUsersRoute
  AuthedAIndexRoute: typeof AuthedAIndexRoute
}

const AuthedARouteRouteChildren: AuthedARouteRouteChildren = {
  AuthedAUsersRoute: AuthedAUsersRoute,
  AuthedAIndexRoute: AuthedAIndexRoute,
}

const AuthedARouteRouteWithChildren = AuthedARouteRoute._addFileChildren(
  AuthedARouteRouteChildren,
)

interface AuthedRouteRouteChildren {
  AuthedARouteRoute: typeof AuthedARouteRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedARouteRoute: AuthedARouteRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestIndexRoute: typeof GuestIndexRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestIndexRoute: GuestIndexRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
